#- name: Wgeting .deb
#  shell: wget "https://github.com/scaleway/scaleway-cli/releases/download/v1.20/scw_1.20_${ARCH}.deb" -O /tmp/scw.deb

#- name: DPKG install v1
#  become: true
#  apt:
#    deb: "https://github.com/scaleway/scaleway-cli/releases/download/v1.20/scw_1.20_{{ arch }}.deb"
#sudo dpkg -i /tmp/scw.deb && rm -f /tmp/scw.deb

- name: Installing scw v2
  become: true
  shell: 'sudo curl -o /usr/local/bin/scw -L "https://github.com/scaleway/scaleway-cli/releases/download/v2.0.0-beta.2/scw-2-0-0-beta-2-linux-x86_64"'

- name: Adding permissions
  become: true
  shell: "sudo chmod +x /usr/local/bin/scw"
